#!/bin/sh

SEARCH=$(echo "$1" | sed 's/:/-/g' | cut -c-8 | tr '[:lower:]' '[:upper:]')

if [ "$SEARCH" = "52-54-00" ]; then
    echo "QEMU virtual address"
elif [ "$SEARCH" = "00-16-3E" ]; then
    echo "XEN virtual address"
else
    DATA=$(grep -i "$SEARCH" <"/usr/share/ieee-data/oui.txt")
    echo "$DATA" | grep "(hex)" | sed 's/(hex)//g' | sed 's/\t//g' |
        sed 's/  / /g'
fi
